version: '3'

services:
  nodejs:
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
  
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: thisisademo
    ports:
      - "5432:5432"
    volumes:
      - ./src/data/sql:/docker-entrypoint-initdb.d