version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app/src
  
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: thisisademo